# file: drawining.kv
<DrawingSpace>:
    canvas:
        Ellipse:
            pos: 10, 10
            size: 80, 80
            source: 'kivy.png'
        Rectangle:
            pos: 110, 110
            size: 80, 80
            source: 'kivy.png'
        Color:
            rgba: 0, 0, 1, .75
        Rectangle:
            pos: 210, 210
            size: 80, 80
            source: 'kivy.png'
        Rectangle:
            pos: 310, 10
            size: 80, 80
            source: 'kivy.png'